.PHONY: dev build install clean format lint check test test-watch

dev:
	npm run dev

build:
	npm run build

install:
	npm install

clean:
	rm -rf node_modules

format:
	npm run format

lint:
	npm run lint

check:
	npm run check

test:
	npm run test

test-watch:
	npm run test:watch
